[package]
name = "runtime-interface"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
wasm-types = { workspace = true }
ir = { workspace = true }
cee-scape = { workspace = true }
