[package]
name = "gen_util"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = "2.0.78"
