stages:          
  - build
  - test

rust-latest:       
  stage: build
  script:
    - cargo build --release

#msrv disabled for now
#rust-msrv:       
#  stage: build
#  script:
#    - cargo build --verbose

cargo-test:   
  stage: test
  script:
    - cargo test --verbose

cargo-clippy:   
  stage: test  
  variables:
    RUSTFLAGS: "-Dwarnings"  
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features

