stages:          
  - build
  - test

rust-latest:       
  stage: build
  image: rust:1.78
  script:
    - cargo build --release

rust-msrv:       
  stage: build
  image: rust:1.75
  script:
    - cargo build --verbose

cargo-test:   
  stage: test
  image: rust:1.78  
  script:
    - cargo test --verbose

cargo-clippy:   
  stage: test  
  image: rust:1.78
  variables:
    RUSTFLAGS: "-Dwarnings"  
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features

