stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-rust-latest:
  stage: build
  image: rust:1.78
  script:
    - cargo build --release
  artifacts:
    paths:
      - "target/"
  tags:
    - lukas-debian-runner

cargo-test:
  stage: test
  script:
    - cargo test
  dependencies:
    - build-rust-latest
  tags:
    - lukas-debian-runner

cargo-clippy:
  stage: test
  variables:
    RUSTFLAGS: "-Dwarnings"
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features
  allow_failure: true
  dependencies:
    - build-rust-latest
  tags:
    - lukas-debian-runner
