workspace = { members = [ "fuzz", "interpreter", "ir", "parser", "tests/gen_util", "wasm-types"] }

[package]
name = "wasm_rt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
log = "0.4.21"
simplelog = "0.12.2"
thiserror = "1.0.60"
wasm-types = { path = "./wasm-types" }
parser = { path = "./parser" }

[dev-dependencies]
wast = "206.0.0"
gen_util = { path = "./tests/gen_util" }
criterion = "0.3"
wasmparser = "0.207.0"

[[bench]]
name = "parser_bench"
harness = false
