workspace = { members = [ "fuzz", "runtime-lib", "interpreter", "ir", "parser", "tests/gen_util", "wasm-types", "loader", "runtime-interface"] }

[package]
name = "wasm_rt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runtime-lib = { path = "runtime-lib" }
simplelog = "0.12.2"
wasm-types = { path = "./wasm-types" }
parser = { path = "./parser" }
loader = { path = "./loader" }
interpreter = { path = "./interpreter" }
ir = { path = "./ir" }
log = "0.4.21"
runtime-interface = { version = "0.1.0", path = "runtime-interface" }

[dev-dependencies]
wast = "206.0.0"
gen_util = { path = "./tests/gen_util" }
criterion = "0.3"
wasmparser = "0.207.0"
test-log = "0.2.16"

[[bench]]
name = "parser_bench"
harness = false

[[bin]]
name = "wasm_rt"
path = "./bin/main.rs"

[profile.release]
debug = true
