[package]
name = "loader"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bitcode = { workspace = true }
ir = { workspace = true }
memmap2 = { workspace = true }
thiserror = { workspace = true }
