[package]
name = "ir"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.63"
wasm-types = { path = "../wasm-types" }
once_cell = "1.19.0"
serde = { version = "1.0.208", features = ["derive"] }
