[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
thiserror = "1.0.63"
wasm-types = { path = "../wasm-types" }
ir = { path = "../ir" }
loader = { path = "../loader" }
itertools = "0.13.0"
