[package]
name = "sightglass-connector"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasi = { workspace = true }
resource-buffer = { workspace = true }
runtime-lib = { workspace = true }
anyhow = "1.0.86"
