[package]
name = "sightglass-connector"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ir = { workspace = true }
wasi = { workspace = true }
loader = { workspace = true }
runtime-lib = { workspace = true }
anyhow = "1.0.86"
