[package]
name = "resource-buffer"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
memmap2 = { workspace = true }
thiserror = { workspace = true }
