[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.60"
wasm-types = { path = "../wasm-types" }
parser = { path = "../parser" }
ir = { path = "../ir" }
runtime-interface = { path = "../runtime-interface" }

[profile.release]
lto = "fat"
