[package]
name = "sightglass-connector"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.86"
ir = { version = "0.1.0", path = "../../ir" }
runtime-lib = { version = "0.1.0", path = "../../runtime-lib" }
